import { ASSETS } from "../assets";
import { REGIONS } from "../data/regions";

export interface HudState { speed: number; nitro: number; lap: number; totalLaps: number; position: number; countdown: number | null; weather: string; raceState: "menu" | "countdown" | "racing" | "finished"; graphics: "HIGH" | "MEDIUM" | "LOW"; warning?: string; }

export class HudController {
  private readonly root: HTMLElement; private readonly speed: HTMLElement; private readonly nitro: HTMLElement; private readonly position: HTMLElement; private readonly lap: HTMLElement; private readonly countdown: HTMLElement; private readonly message: HTMLElement; private readonly menu: HTMLElement; private readonly weather: HTMLElement; private readonly profileButtons: HTMLElement[];
  constructor(callbacks: { onStart: () => void; onProfile: (profile: "HIGH" | "MEDIUM" | "LOW") => void; onWeather: () => void }) {
    const root = document.querySelector<HTMLElement>("#game-ui"); if (!root) throw new Error("Game UI mount not found"); this.root = root;
    const mapCards = REGIONS.map((region) => `<span class="region-chip ${region.unlocked ? "is-open" : "is-locked"}">${region.unlocked ? "01" : "—"} ${region.title}</span>`).join("");
    root.innerHTML = `<section class="game-menu is-visible" data-menu><div class="menu-art" style="background-image:url('${ASSETS.visualTarget}')"></div><div class="menu-scrim"></div><div class="menu-side-rule"></div><div class="menu-content"><div class="brand-lockup"><img src="${ASSETS.logo}" alt="" /><span>UZBEKISTAN<br/>AUTO RACE</span></div><p class="eyebrow">01 / OCHIQ BOSQICH</p><h1>TOSHKENT<br/><em>HALQASI</em></h1><p class="menu-copy">Tog‘oldi magistrali. Uch aylana. To‘rtta raqib. Burilish oldidan nitroni saqla.</p><div class="menu-meta"><span>3 AYLANMA</span><span>·</span><span>ANDROID READY</span><span>·</span><span>3D DEMO</span></div><button class="launch-button" type="button" data-start><b>START CHIZIG‘IGA CHIQ</b><span>ENTER</span></button><p class="controls-hint">KOMPYUTER: WASD / STRELKA · NITRO: SHIFT</p></div><div class="region-strip"><span class="strip-label">VILOYATLAR / 01—12</span><div>${mapCards}</div></div></section><section class="race-hud" data-hud><div class="hud-top"><div class="location-tag"><img src="${ASSETS.logo}" alt="" /><div><span>TOSHKENT / 01</span><b>HALQA YO‘LI</b></div></div><div class="race-status"><span>POZITSIYA</span><b data-position>5<small>/5</small></b><i></i><span>AYLANA</span><b data-lap>1<small>/3</small></b></div></div><div class="countdown" data-countdown></div><div class="finish-message" data-message></div><div class="hud-bottom"><div class="weather-card"><button type="button" data-weather><span>OB-HAVO</span><b data-weather-name>KUN</b></button><small>TEGIB ALMASHTIR</small></div><div class="speed-cluster"><div class="speed-value"><b data-speed>000</b><span>KM/H</span></div><div class="nitro-track"><i data-nitro></i></div><span class="nitro-label">NITRO</span></div><div class="graphics-card"><span>GRAFIKA</span><div><button type="button" data-profile="HIGH">H</button><button type="button" data-profile="MEDIUM">M</button><button type="button" data-profile="LOW">L</button></div></div></div><div class="touch-controls" aria-label="Mobil boshqaruvlar"><div class="steer-controls"><button class="touch-control" data-drive-action="left" type="button" aria-label="Chapga burish">‹</button><button class="touch-control" data-drive-action="right" type="button" aria-label="O‘ngga burish">›</button></div><div class="pedal-controls"><button class="touch-control brake" data-drive-action="brake" type="button">TORMOZ</button><button class="touch-control nitro" data-drive-action="nitro" type="button">N₂O</button><button class="touch-control throttle" data-drive-action="throttle" type="button">GAZ</button></div></div></section>`;
    this.speed = this.require("[data-speed]"); this.nitro = this.require("[data-nitro]"); this.position = this.require("[data-position]"); this.lap = this.require("[data-lap]"); this.countdown = this.require("[data-countdown]"); this.message = this.require("[data-message]"); this.menu = this.require("[data-menu]"); this.weather = this.require("[data-weather-name]"); this.profileButtons = Array.from(root.querySelectorAll<HTMLElement>("[data-profile]"));
    this.require("[data-start]").addEventListener("click", callbacks.onStart); this.require("[data-weather]").addEventListener("click", callbacks.onWeather); this.profileButtons.forEach((button) => button.addEventListener("click", () => callbacks.onProfile(button.dataset.profile as "HIGH" | "MEDIUM" | "LOW")));
  }
  private require(selector: string): HTMLElement { const element = this.root.querySelector<HTMLElement>(selector); if (!element) throw new Error(`Missing HUD element: ${selector}`); return element; }
  update(state: HudState): void {
    this.speed.textContent = state.speed.toString().padStart(3, "0"); this.nitro.style.width = `${Math.max(0, Math.min(100, state.nitro))}%`; this.position.innerHTML = `${state.position}<small>/5</small>`; this.lap.innerHTML = `${Math.min(state.lap, state.totalLaps)}<small>/${state.totalLaps}</small>`; this.weather.textContent = state.weather; this.countdown.textContent = state.countdown ? String(Math.max(1, Math.ceil(state.countdown))) : ""; this.menu.classList.toggle("is-visible", state.raceState === "menu"); this.message.textContent = state.raceState === "finished" ? "MARRA. TOSHKENT BOSQICHI YAKUNLANDI." : (state.warning ?? ""); this.message.classList.toggle("is-visible", state.raceState === "finished" || Boolean(state.warning)); this.profileButtons.forEach((button) => button.classList.toggle("is-active", button.dataset.profile === state.graphics));
  }
  dispose(): void { this.root.innerHTML = ""; }
}

