import "./hud.css";
import { ASSETS } from "../assets";
import { CARS, PAINTS } from "../data/cars";
import { REGIONS, type RegionConfig } from "../data/regions";
import type { GarageProgress } from "../data/progress";
import type { CameraMode } from "../systems/CameraController";

export interface MapMarker { x: number; y: number; }
export type MenuSection = "race" | "garage" | "regions" | "settings";
export interface HudState {
  speed: number; nitro: number; lap: number; totalLaps: number; position: number; countdown: number | null; weather: string; raceState: "menu" | "countdown" | "racing" | "paused" | "finished"; graphics: "HIGH" | "MEDIUM" | "LOW"; elapsed: number; cameraMode: CameraMode; drifting: boolean; playerMap: MapMarker; rivalsMap: MapMarker[]; highestUnlockedRegion: number; selectedRegion: RegionConfig; garage: GarageProgress; warning?: string;
}
interface Callbacks {
  onStart: () => void; onProfile: (profile: "HIGH" | "MEDIUM" | "LOW") => void; onWeather: () => void; onCamera: () => void; onPause: () => void; onRestart: () => void; onContinue: () => void; onSection: (section: MenuSection) => void; onSelectRegion: (regionId: string) => void; onSelectCar: (carId: string) => void; onPaint: (paint: string) => void; onUpgrade: (kind: "engine" | "handling" | "nitro") => void;
}
function formatTime(totalSeconds: number): string { const minutes = Math.floor(totalSeconds / 60).toString().padStart(2, "0"); const seconds = Math.floor(totalSeconds % 60).toString().padStart(2, "0"); const hundredths = Math.floor((totalSeconds % 1) * 100).toString().padStart(2, "0"); return `${minutes}:${seconds}.${hundredths}`; }

export class HudController {
  private readonly root: HTMLElement; private readonly speed: HTMLElement; private readonly nitro: HTMLElement; private readonly position: HTMLElement; private readonly lap: HTMLElement; private readonly countdown: HTMLElement; private readonly message: HTMLElement; private readonly menu: HTMLElement; private readonly weather: HTMLElement; private readonly timer: HTMLElement; private readonly camera: HTMLElement; private readonly drift: HTMLElement; private readonly results: HTMLElement; private readonly resultPosition: HTMLElement; private readonly resultTime: HTMLElement; private readonly resultNext: HTMLElement; private readonly playerMarker: HTMLElement; private readonly rivalMarkers: HTMLElement[]; private readonly profileButtons: HTMLElement[]; private readonly regionButtons: HTMLElement[]; private readonly garageCars: HTMLElement[]; private readonly paintButtons: HTMLElement[]; private readonly upgradeButtons: HTMLElement[]; private readonly panelTitle: HTMLElement; private currentSection: MenuSection = "race";

  constructor(callbacks: Callbacks) {
    const root = document.querySelector<HTMLElement>("#game-ui"); if (!root) throw new Error("Game UI mount not found"); this.root = root;
    const regionStrip = REGIONS.map((region, index) => `<button class="region-chip" data-region="${region.id}"><span>${(index + 1).toString().padStart(2, "0")}</span> ${region.title}</button>`).join("");
    const garageCars = CARS.map((car) => `<button class="garage-car" data-car="${car.id}" type="button"><i class="car-silhouette ${car.bodyStyle}"></i><span>${car.name}</span></button>`).join("");
    const paintButtons = PAINTS.map((paint) => `<button class="paint-dot" data-paint="${paint}" type="button" style="--paint:${paint}" aria-label="${paint}"></button>`).join("");
    const regionCards = REGIONS.map((region, index) => `<button class="region-card" data-region="${region.id}" type="button"><span>${(index + 1).toString().padStart(2, "0")}</span><b>${region.title}</b><small>${region.subtitle}</small><i>QULFLANGAN</i></button>`).join("");
    root.innerHTML = `
      <section class="game-menu is-visible" data-menu>
        <div class="menu-art" style="background-image:url('${ASSETS.visualTarget}')"></div><div class="menu-scrim"></div><div class="menu-side-rule"></div>
        <div class="menu-content"><div class="brand-lockup"><i class="atlas-mark" aria-hidden="true"></i><span>UZBEKISTAN<br/>AUTO RACE</span></div><div class="menu-nav"><button type="button" data-section="race">POYGA</button><button type="button" data-section="garage">GARAJ</button><button type="button" data-section="regions">VILOYATLAR</button><button type="button" data-section="settings">SOZLAMALAR</button></div><p class="eyebrow" data-stage>01 / OCHIQ BOSQICH</p><h1 data-region-title>TOSHKENT<br/><em>HALQASI</em></h1><p class="menu-copy" data-region-copy>Tog‘oldi magistrali. Uch aylana. To‘rtta raqib. Burilish oldidan nitroni saqla.</p><div class="menu-meta"><span>3 AYLANMA</span><span>·</span><span>ANDROID READY</span><span>·</span><span>DRIVING DEMO</span></div><button class="launch-button" type="button" data-start><b>POYGANI BOSHLASH</b><span>ENTER</span></button><p class="controls-hint">TELEFON: RUL / GAZ / TORMOZ · KAMERA: CAM</p></div>
        <div class="region-strip"><span class="strip-label">VILOYATLAR / 01—12</span><div>${regionStrip}</div></div>
        <section class="menu-panel" data-panel="garage"><button class="panel-close" data-section="race">×</button><p class="panel-kicker">GARAJ / TANLASH VA TUNING</p><h2 data-panel-title>COBALT</h2><div class="garage-layout"><div class="garage-preview"><i class="garage-car-large sedan" data-garage-preview></i><p data-garage-description>Muvozanatli shahar sedani</p><div class="garage-stats"><span>TEZLANISH<i data-stat-accel></i></span><span>TEZLIK<i data-stat-speed></i></span><span>HANDLING<i data-stat-handling></i></span></div></div><div class="garage-list">${garageCars}</div></div><div class="garage-tuning"><div><b>RANG</b><span class="paint-row">${paintButtons}</span></div><div class="upgrade-row"><button type="button" data-upgrade="engine">DVIGATEL <i data-upgrade-engine>0/3</i></button><button type="button" data-upgrade="handling">BOSHQARUV <i data-upgrade-handling>0/3</i></button><button type="button" data-upgrade="nitro">NITRO <i data-upgrade-nitro>0/3</i></button></div></div></section>
        <section class="menu-panel" data-panel="regions"><button class="panel-close" data-section="race">×</button><p class="panel-kicker">VILOYATLAR / OCHILISH YO‘LI</p><h2>MARSHRUT<br/><em>ATLAS</em></h2><div class="region-grid">${regionCards}</div></section>
        <section class="menu-panel" data-panel="settings"><button class="panel-close" data-section="race">×</button><p class="panel-kicker">SOZLAMALAR</p><h2>GRAFIKA<br/><em>VA OVOZ</em></h2><div class="settings-block"><b>GRAFIK REJIM</b><div class="settings-graphics"><button type="button" data-profile="HIGH">HIGH</button><button type="button" data-profile="MEDIUM">MEDIUM</button><button type="button" data-profile="LOW">LOW</button></div><p>Low rejimda Android qurilmalarida yanada barqaror driving uchun render yuklamasi kamayadi.</p></div></section>
      </section>
      <section class="race-hud" data-hud>
        <div class="telemetry-stack"><div class="location-tag"><i class="atlas-mini" aria-hidden="true"></i><div><span data-hud-region>TOSHKENT / 01</span><b data-hud-track>HALQA YO‘LI</b></div></div><div class="minimap-card"><span class="minimap-title">MINI XARITA</span><div class="minimap-route"></div><i class="map-dot player" data-map-player></i><i class="map-dot rival" data-map-rival="0"></i><i class="map-dot rival" data-map-rival="1"></i><i class="map-dot rival" data-map-rival="2"></i><i class="map-dot rival" data-map-rival="3"></i></div></div>
        <div class="race-status"><span>POZITSIYA</span><b data-position>5<small>/5</small></b><i></i><span>AYLANA</span><b data-lap>1<small>/3</small></b></div><div class="race-timer" data-time>00:00.00</div><div class="camera-card"><button type="button" data-camera>KAMERA: <span data-camera-name>ORQA</span></button><button type="button" data-pause><span data-pause-name>PAUZA</span></button></div><div class="countdown" data-countdown></div><div class="finish-message" data-message></div><div class="drift-badge" data-drift>DRIFT</div>
        <div class="hud-bottom"><div class="weather-card"><button type="button" data-weather><span>OB-HAVO</span><b data-weather-name>KUN</b></button><small>TEGIB ALMASHTIR</small></div><div class="speed-cluster"><div class="speed-value"><b data-speed>000</b><span>KM/H</span></div><div class="nitro-track"><i data-nitro></i></div><span class="nitro-label">NITRO</span></div><div class="graphics-card"><span>GRAFIKA</span><div><button type="button" data-profile="HIGH">H</button><button type="button" data-profile="MEDIUM">M</button><button type="button" data-profile="LOW">L</button></div></div></div><div class="touch-controls" aria-label="Mobil boshqaruvlar"><div class="steer-controls"><button class="touch-control" data-drive-action="left" type="button" aria-label="Chapga burish">‹</button><button class="touch-control" data-drive-action="right" type="button" aria-label="O‘ngga burish">›</button></div><div class="pedal-controls"><button class="touch-control brake" data-drive-action="brake" type="button">TORMOZ</button><button class="touch-control nitro" data-drive-action="nitro" type="button">N₂O</button><button class="touch-control throttle" data-drive-action="throttle" type="button">GAZ</button></div></div>
      </section>
      <section class="results-panel" data-results><div class="results-card"><p class="results-kicker" data-result-kicker>TOSHKENT / NATIJA</p><h2>MARRA<br/><em>YAKUN</em></h2><div class="results-stats"><span>JOYLASHUV<b data-result-position>—</b></span><span>VAQT<b data-result-time>00:00.00</b></span></div><p class="unlock-note"><b data-result-next>SIRDARYO BOSQICHI OCHILDI.</b> Keyingi viloyat yo‘nalishi profilingizda saqlandi.</p><div class="result-actions"><button type="button" class="secondary" data-restart>QAYTA POYGA</button><button type="button" data-continue>KEYINGI VILOYAT</button></div></div></section>`;
    this.speed = this.require("[data-speed]"); this.nitro = this.require("[data-nitro]"); this.position = this.require("[data-position]"); this.lap = this.require("[data-lap]"); this.countdown = this.require("[data-countdown]"); this.message = this.require("[data-message]"); this.menu = this.require("[data-menu]"); this.weather = this.require("[data-weather-name]"); this.timer = this.require("[data-time]"); this.camera = this.require("[data-camera-name]"); this.drift = this.require("[data-drift]"); this.results = this.require("[data-results]"); this.resultPosition = this.require("[data-result-position]"); this.resultTime = this.require("[data-result-time]"); this.resultNext = this.require("[data-result-next]"); this.playerMarker = this.require("[data-map-player]"); this.rivalMarkers = Array.from(root.querySelectorAll<HTMLElement>("[data-map-rival]")); this.profileButtons = Array.from(root.querySelectorAll<HTMLElement>("[data-profile]")); this.regionButtons = Array.from(root.querySelectorAll<HTMLElement>("[data-region]")); this.garageCars = Array.from(root.querySelectorAll<HTMLElement>("[data-car]")); this.paintButtons = Array.from(root.querySelectorAll<HTMLElement>("[data-paint]")); this.upgradeButtons = Array.from(root.querySelectorAll<HTMLElement>("[data-upgrade]")); this.panelTitle = this.require("[data-panel-title]");
    this.require("[data-start]").addEventListener("click", callbacks.onStart); this.require("[data-weather]").addEventListener("click", callbacks.onWeather); this.require("[data-camera]").addEventListener("click", callbacks.onCamera); this.require("[data-pause]").addEventListener("click", callbacks.onPause); this.require("[data-restart]").addEventListener("click", callbacks.onRestart); this.require("[data-continue]").addEventListener("click", callbacks.onContinue); root.querySelectorAll<HTMLElement>("[data-section]").forEach((button) => button.addEventListener("click", () => callbacks.onSection(button.dataset.section as MenuSection))); this.profileButtons.forEach((button) => button.addEventListener("click", () => callbacks.onProfile(button.dataset.profile as "HIGH" | "MEDIUM" | "LOW"))); this.regionButtons.forEach((button) => button.addEventListener("click", () => callbacks.onSelectRegion(button.dataset.region ?? ""))); this.garageCars.forEach((button) => button.addEventListener("click", () => callbacks.onSelectCar(button.dataset.car ?? ""))); this.paintButtons.forEach((button) => button.addEventListener("click", () => callbacks.onPaint(button.dataset.paint ?? ""))); this.upgradeButtons.forEach((button) => button.addEventListener("click", () => callbacks.onUpgrade(button.dataset.upgrade as "engine" | "handling" | "nitro")));
  }
  private require(selector: string): HTMLElement { const element = this.root.querySelector<HTMLElement>(selector); if (!element) throw new Error(`Missing HUD element: ${selector}`); return element; }
  private place(marker: HTMLElement, point: MapMarker): void { marker.style.left = `${point.x}%`; marker.style.top = `${point.y}%`; }
  openSection(section: MenuSection): void { this.currentSection = section; this.root.querySelectorAll<HTMLElement>("[data-panel]").forEach((panel) => panel.classList.toggle("is-visible", panel.dataset.panel === section)); this.root.querySelectorAll<HTMLElement>(".menu-nav [data-section]").forEach((button) => button.classList.toggle("is-active", button.dataset.section === section)); }

  update(state: HudState): void {
    const selectedCar = CARS.find((car) => car.id === state.garage.selectedCarId) ?? CARS[0]; const nextRegion = REGIONS[Math.min(REGIONS.length - 1, state.selectedRegion && REGIONS.findIndex((region) => region.id === state.selectedRegion.id) + 1)];
    this.speed.textContent = state.speed.toString().padStart(3, "0"); this.nitro.style.width = `${Math.max(0, Math.min(100, state.nitro))}%`; this.position.innerHTML = `${state.position}<small>/5</small>`; this.lap.innerHTML = `${Math.min(state.lap, state.totalLaps)}<small>/${state.totalLaps}</small>`; this.weather.textContent = state.weather; this.timer.textContent = formatTime(state.elapsed); this.camera.textContent = state.cameraMode === "CHASE" ? "ORQA" : "ICHKI"; this.require("[data-pause-name]").textContent = state.raceState === "paused" ? "DAVOM" : "PAUZA"; this.countdown.textContent = state.countdown ? String(Math.max(1, Math.ceil(state.countdown))) : "";
    this.menu.classList.toggle("is-visible", state.raceState === "menu"); this.results.classList.toggle("is-visible", state.raceState === "finished"); this.message.textContent = state.warning ?? ""; this.message.classList.toggle("is-visible", Boolean(state.warning)); this.drift.classList.toggle("is-active", state.drifting); this.profileButtons.forEach((button) => button.classList.toggle("is-active", button.dataset.profile === state.graphics)); this.place(this.playerMarker, state.playerMap); state.rivalsMap.forEach((point, index) => { if (this.rivalMarkers[index]) this.place(this.rivalMarkers[index], point); });
    this.require("[data-stage]").textContent = `${(REGIONS.findIndex((region) => region.id === state.selectedRegion.id) + 1).toString().padStart(2, "0")} / ${state.selectedRegion.id === "sirdaryo" ? "MIRZACHO‘L SPRINTI" : "OCHIQ BOSQICH"}`; this.require("[data-region-title]").innerHTML = `${state.selectedRegion.title}<br/><em>${state.selectedRegion.subtitle.toUpperCase()}</em>`; this.require("[data-region-copy]").textContent = state.selectedRegion.id === "sirdaryo" ? "Mirzacho‘lning keng dala va qishloq yo‘llari. Tezlikni ushla, kanallar yonida ehtiyot bo‘l." : "Tog‘oldi magistrali. Uch aylana. To‘rtta raqib. Burilish oldidan nitroni saqla."; this.require("[data-hud-region]").textContent = `${state.selectedRegion.title} / ${(REGIONS.findIndex((region) => region.id === state.selectedRegion.id) + 1).toString().padStart(2, "0")}`; this.require("[data-hud-track]").textContent = state.selectedRegion.subtitle.toUpperCase();
    this.regionButtons.forEach((button) => { const index = REGIONS.findIndex((region) => region.id === button.dataset.region); const unlocked = index <= state.highestUnlockedRegion; button.classList.toggle("is-unlocked-now", unlocked); button.classList.toggle("is-selected", button.dataset.region === state.selectedRegion.id); if (button.classList.contains("region-card")) { button.classList.toggle("is-locked", !unlocked); const flag = button.querySelector("i"); if (flag) flag.textContent = unlocked ? "OCHIQ" : "QULFLANGAN"; } });
    this.garageCars.forEach((button) => button.classList.toggle("is-selected", button.dataset.car === selectedCar.id)); this.paintButtons.forEach((button) => button.classList.toggle("is-selected", button.dataset.paint === state.garage.paint)); this.panelTitle.textContent = selectedCar.name; this.require("[data-garage-description]").textContent = selectedCar.description; const preview = this.require("[data-garage-preview]"); preview.className = `garage-car-large ${selectedCar.bodyStyle}`; preview.style.setProperty("--car-paint", state.garage.paint); this.require("[data-stat-accel]").style.width = `${Math.min(100, selectedCar.acceleration * 4 + state.garage.engineLevel * 7)}%`; this.require("[data-stat-speed]").style.width = `${Math.min(100, selectedCar.maxSpeed + state.garage.engineLevel * 4)}%`; this.require("[data-stat-handling]").style.width = `${Math.min(100, selectedCar.handling * 70 + state.garage.handlingLevel * 7)}%`; this.require("[data-upgrade-engine]").textContent = `${state.garage.engineLevel}/3`; this.require("[data-upgrade-handling]").textContent = `${state.garage.handlingLevel}/3`; this.require("[data-upgrade-nitro]").textContent = `${state.garage.nitroLevel}/3`;
    this.resultPosition.textContent = `${state.position}/5`; this.resultTime.textContent = formatTime(state.elapsed); this.require("[data-result-kicker]").textContent = `${state.selectedRegion.title} / NATIJA`; this.resultNext.textContent = `${nextRegion.title} BOSQICHI OCHILDI.`;
  }
  dispose(): void { this.root.innerHTML = ""; }
}
